export default {
  client: {
    ASK_LOGIN: 'ASK_LOGIN',
    ASK_LOGOUT: 'ASK_LOGOUT',
    DENY_LOGOUT: 'DENY_LOGOUT',
    DENY_WS_CLOSE_WHILE_LOGGEDOUT: 'DENY_WS_CLOSE_WHILE_LOGGEDOUT',
    FAIL_SEND_WHILE_DISCONNECTED: 'SEND_FAIL_WHILE_DISCONNECTED',
    SEND_CHAT: 'SEND_CHAT',
  },
  server: {
    SERVER_LOGGEDIN: 'SERVER_LOGGEDIN',
    SERVER_LOGOUT: 'SERVER_LOGOUT',
    SERVER_WELCOME: 'SERVER_WELCOME',
    SERVER_BROADCAST_CHAT: 'SERVER_BROADCAST_CHAT',
    SERVER_BROADCAST_ENTRY: 'SERVER_BROADCAST_ENTRY',
    SERVER_BROADCAST_LEAVE: 'SERVER_BROADCAST_LEAVE',
    ASK_WS_OPEN: 'ASK_WS_OPEN',
    ASK_WS_CLOSE: 'ASK_WS_CLOSE',
    WS_OPEN: 'WS_OPEN',
    WS_CLOSE: 'WS_CLOSE',
  }
}