export default {
  client: {
    ASK_LOGIN: 'ASK_LOGIN',
    ASK_LOGOUT: 'ASK_LOGOUT',
    FAIL_LOGOUT_WHILE_CONNECTED: 'FAIL_LOGOUT_WHILE_CONNECTED',
    FAIL_CONNECT_WHILE_LOGGEDOUT: 'FAIL_CONNECT_WHILE_LOGGEDOUT',
    FAIL_SEND_WHILE_DISCONNECTED: 'SEND_FAIL_WHILE_DISCONNECTED',
    SEND_CHAT: 'SEND_CHAT',
    ASK_WS_OPEN: 'ASK_WS_OPEN',
    ASK_WS_CLOSE: 'ASK_WS_CLOSE',
  },
  server: {
    LOGGEDIN: 'LOGGEDIN',
    LOGGEDOUT: 'LOGGEDOUT',
    UNICAST_WELCOME: 'UNICAST_WELCOME',
    BROADCAST_CHAT: 'BROADCAST_CHAT',
    BROADCAST_ENTRY: 'BROADCAST_ENTRY',
    BROADCAST_LEAVE: 'BROADCAST_LEAVE',
  },
  ws: {
    OPEN: 'OPEN',
    CLOSE: 'CLOSE',
    FAIL_LOGOUT_WHILE_WS_CONNECTED: 'FAIL_LOGOUT_WHILE_WS_CONNECTED',
  }
}